[package]
name = "carbon_v3"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.3.1"
alexandria_storage = { git = "https://github.com/tekkac/alexandria", branch = "feat/interpolation-fast" }
alexandria_numeric = { git = "https://github.com/tekkac/alexandria", branch = "feat/interpolation-fast" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }
token = { git = "https://github.com/dojoengine/origami.git",  rev = "60d8eb7875d4c0367d75a337b0ce607ee5992e4b" }

[[target.starknet-contract]]
